name: Publish Articles to Production

on:
  push:
    branches:
      - main  # Trigger the workflow on push to master branch
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  publish-articles:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for Markdown Parsing
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Dependencies for the Node.js Script
      - name: Install Dependencies
        run: npm install gray-matter axios

      # Step 4: Run the Publish Articles Script
      - name: Publish Articles
        run: node publishArticles.js
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
